version: "3.9"
services:
    mysql:
      image: mysql:8.0.28
      platform: linux/amd64
      container_name: mysql-go
      ports:
        - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: development
        TZ: "Asia/Tokyo"
      volumes:
        - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      networks:
        - app_network

    app:
        container_name: "go-app-1"
        build: ./app
        volumes:
          - ./:/usr/src
        ports:
          - "8080:8080"
        networks:
          - app_network
        depends_on:
          - mysql

    app2:
        container_name: "go-app-2"
        build: ./app2
        volumes:
          - ./:/usr/src
        ports:
          - "8081:8081"
        networks:
          - app_network
        depends_on:
          - mysql
networks:
  app_network:
    driver: bridge